# 3600 ~= 6 min if 0.0000277
number_of_steps = 3600
human_diameter = 25
map_pixel_size = 4

# ----------------------------------------------------------------------------
[simulation]
# 1=1h; 0.000277 ~= 1s
# 0.0000277 ~= 0.1s
time_step = 0.0000277
bound_space = true
min_bound = -50
max_bound = 50
run_mechanical_interactions = false
show_simulation_step = false
leaking_edges = false
calculate_gradients = false

# ----------------------------------------------------------------------------
[visualization]
export = true
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "Human"
    additional_data_members = [ "state_" ]
