number_of_steps = 2000
human_diameter = 50
map_pixel_size = 2

# ----------------------------------------------------------------------------
[simulation]
time_step = 1
bound_space = true
min_bound = -2500
max_bound = 2500
run_mechanical_interactions = true
show_simulation_step = false
calculate_gradients = false

# ----------------------------------------------------------------------------
[visualization]
export = false
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "Human"
    additional_data_members = [ "state_" ]
