# 3600 = 30min
number_of_steps = 2
human_diameter = 25
map_pixel_size = 4

# ----------------------------------------------------------------------------
[simulation]
# 1=1h; 0.000277 ~= 1s
# 0.00014 ~= 0.5s
time_step = 0.00014
bound_space = true
min_bound = -650
max_bound = 650
run_mechanical_interactions = false
show_simulation_step = false
leaking_edges = false
calculate_gradients = false

# ----------------------------------------------------------------------------
[visualization]
export = true
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "Human"
    additional_data_members = [ "state_" ]

    [[visualize_diffusion]]
    name = "aerosol"
